### ISSUE TITLE
access token issue 

### ISSUE THREAD

**Issue by subhans3tech** [Azure-Samples/active-directory-b2c-ios-swift-native-msal#2]
"Error Domain=MSALErrorDomain Code=-42105 "(null)" UserInfo={MSALErrorDescriptionKey=Token response is missing the access token"This is the error when i run the code with my credentials .Could you please tell me where is the actual problem.in configuration of AAD b2c or in code side .
Regards,
Subhan Fazal
@brandwe

**Comment by brandwe** [comment]
@subhans3tech This feels like server side issue. I'm not aware of any flows where you don't get an access token. If you're still having the issue email me directly and we'll take a look. brandwe@microsoft.com

**Comment by parakhj** [comment]
@subhans3tech Are you getting an id token?

**Comment by subhans3tech** [comment]
![access token scope](https://user-images.githubusercontent.com/19686311/28208978-e53889d0-68a9-11e7-9c96-ae53ddbd8d78.png)
this is the scope we set in b2b directory .and in code write the following line 
["https:myb2ciosapp.onmicrosoft.com/openid"]

**Comment by parakhj** [comment]
@subhans3tech you need to first [set up a web api](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-app-registration#register-a-web-api), and set up your published scopes (step 9 in that article). Then you need to [grant the scopes](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-access-tokens#granting-permissions-to-a-web-api) to your iosapp registration. Then when you are running the policy, you will see that the "Select resource" is not grayed out, and you will be able to select the API

**Comment by subhans3tech** [comment]
@parakhj  i have  done all these steps before posting the question could please share some screen shots with me or  i can mail you screen shots of my configurations?

**Comment by nitisha1** [comment]
@subhans3tech  - I'm facing the same issue.Did you solved it?

**Comment by subhans3tech** [comment]
https://mytestapiios.azurewebsites.net/hello#id_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ilg1ZVhrNHh5b2pORnVtMWtsMll0djhkbE5QNC1jNTdkTzZRR1RWQndhTmsifQ.eyJleHAiOjE1MDAzMDA1MDAsIm5iZiI6MTUwMDI5NjkwMCwidmVyIjoiMS4wIiwiaXNzIjoiaHR0cHM6Ly9sb2dpbi5taWNyb3NvZnRvbmxpbmUuY29tL3RmcC9jNzgzMmI1Ni0yYzUyLTQ4YzktYjljNy01OWZlNWRmNjIyOWQvYjJjXzFfYm90c2lnbmluL3YyLjAvIiwic3ViIjoiMzY2NGI3ZWQtMTE3Mi00YzFiLThkZWUtNjIzMjE0MmUyNWQxIiwiYXVkIjoiNjFmZDRlOGUtZDhhOC00MjVhLWE3OWEtYTAyMDYyMTJkODU5Iiwibm9uY2UiOiJkZWZhdWx0Tm9uY2UiLCJpYXQiOjE1MDAyOTY5MDAsImF1dGhfdGltZSI6MTUwMDI5NjkwMCwiaWRwIjoibGl2ZS5jb20iLCJuYW1lIjoic3ViaGFuIHMzMSIsImdpdmVuX25hbWUiOiJTdWJoYW4iLCJjaXR5IjoiSXNsYW1hYmFkIiwiZW1haWxzIjpbImxhZWVxNTFAb3V0bG9vay5jb20iXSwidGZwIjoiQjJDXzFfYm90c2lnbmluIn0.Epc6hxceplZXHq0GtCjH1oK_4kZcotMC0i3sGzOm_mjujhqxsPoNTt9awH8z5OXI1QbUJbpdUNIqJcBcwmVDnoP1hZRUqnAHiWZlv83l7ev3TOqOxy8OJLCjX0qGBu5e7J1xT9G2botTvFr6Wx8Pg-0ZUtQfg3_TAH0QAYGhF-MWTb5VIt5S4kNMeJ-maIF4qlSdJ-NGlhoFGv6B2zIeqkTeCPdimkQjkqKjzDBSJ8VJo80rg0nh8mE0N2wSClMhS0ubMhZ82UmKG8nTLtRFy9UN58blbANixm-qbkxIDHWC4uNkhMeF4h_CjkBBrKbBeyfuPJ5njeG1Rexnz6qyBA

This is the response I am getting in url when irum from sigun or in run now
.

**Comment by subhans3tech** [comment]
@nitisha1  I am still working on that

**Comment by parakhj** [comment]
@subhans3tech sorry for the late reply. Could you paste the "Run now endpoint" link (just hit the copy button).

Before you copy it - make sure you select "appapi" as the resource and select the three resources.

Just to confirm your scenario:

You are trying to sign into the app "App" and as part of signing in, you want an access token to the web api "Appapi". Is that correct? If so, could you send a screenshot of the "Published Scopes" blade from the Web API registration, and the "Api Access" blade from the Web App registration.

**Comment by subhans3tech** [comment]
this is the url for appapi
 (run now button)https://login.microsoftonline.com/myb2ciosapp.onmicrosoft.com/oauth2/v2.0/authorize?p=B2C_1_botsignin&client_id=70651a06-e952-4812-af05-3160562e3dd6&nonce=defaultNonce&redirect_uri=https%3A%2F%2Fmytestapiios.azurewebsites.net%2Fhello&scope=openid&response_type=id_token&prompt=login 
![image](https://user-images.githubusercontent.com/19686311/28514735-8ddbd1ec-7074-11e7-85f9-f7cc72e61042.png)
This is the url for my App (ios)https://login.microsoftonline.com/myb2ciosapp.onmicrosoft.com/oauth2/v2.0/authorize?p=B2C_1_botsignin&client_id=a3b32c27-0c4b-4360-b420-2498a975fa20&nonce=defaultNonce&redirect_uri=https%3A%2F%2Fmytestapiios.azurewebsites.net%2Fhello&scope=openid&response_type=id_token&prompt=login
![image](https://user-images.githubusercontent.com/19686311/28514760-a533fb1c-7074-11e7-9741-403161650a1b.png)

**Comment by Techmorphian** [comment]
I want to use the scope for Mobile application, so how can i add the scope for a mobile application?

**Comment by parakhj** [comment]
You'll have to grant the native app permissions to your API's scopes. Check out the instructions [here](https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-access-tokens#granting-permissions-to-a-web-api)

**Comment by ihoro** [comment]
I've got this working after I added API as an application, and then allowed native application to access this API with default user_impersonation scope.
