### ISSUE TITLE
Add Swift manifest file to allow using MSAL from Swift Package Manager

### ISSUE THREAD

**Issue by SredzinskiPatryk** [Azure-Samples/active-directory-b2c-ios-swift-native-msal#20]
When you're now trying to use Swift Package Manager to handle iOS dependencies. MSAL is returning an error about missing manifest file. It be nice to be able to use SPM as it is a native solution.

![Zrzut ekranu 2019-11-18 o 09 47 36](https://user-images.githubusercontent.com/32341779/69037632-82d0b500-09e8-11ea-8dd4-ae3abccbe1a6.png)

**Comment by jennyf19** [comment]
thoughts on this @oldalton? Thanks.

**Comment by oldalton** [comment]
This feature request is tracked here: https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/737. Thanks.
