### ISSUE TITLE
Unable to install using Carthage. Is it possible to install this using Cocoapods.

### ISSUE THREAD

**Issue by Jitenderios** [Azure-Samples/active-directory-b2c-ios-swift-native-msal#23]
Hi,

 I need help with these points for setting up Login and Registration on our app from Microsoft. :-
1. Unable to install Azure AD B2C package on iOS project using Carthage as given on this GitHub page.
2. Steps to integrate Azure AD B2C using pods files. (https://cocoapods.org/) ?
3. Steps to integrate Login and Sign-up functionality using Azure AD B2C with azure’s predefined screens on iOS app.
Thanks,
Jitender

**Comment by jennyf19** [comment]
@oldalton @brandwe @jasoncoolmax 
Can you take a look at this? Thanks!
cc: @secorre92 @jmprieur

**Comment by oldalton** [comment]
Thanks for reporting this. What kind of error are you getting with Carthage? It will help us to investigate any possible issues with Carthage integration.

**Comment by Jitenderios** [comment]
Hi @oldalton,
I have worked around with that error and now I am able to install using Carthage on my iOS project. 
The sample project given in this GitHub only shows login using microsoft account. Is there a way i can have the signup page as well along login page?

Thanks,
Jitender

**Comment by jennyf19** [comment]
@Jitenderios What do you mean by "have the signup page as well along with login page"?
