### ISSUE TITLE
Cancel button in toolbar app

### ISSUE THREAD

**Issue by eltonjhony** [Azure-Samples/active-directory-b2c-ios-swift-native-msal#25]
Hi,

Is there a way to remove the CANCEL button in the App left item bar?
<img width="350" alt="Screenshot at Jan 17 10-35-31" src="https://user-images.githubusercontent.com/25302517/72616191-266d1180-3915-11ea-8390-e55203d48299.png">

**Comment by jennyf19** [comment]
fyi: @oldalton

**Comment by oldalton** [comment]
You can create your own fully custom UI by passing MSAL your web view. See documentation here: https://azuread.github.io/microsoft-authentication-library-for-objc/Classes/MSALWebviewParameters.html#/c:objc(cs)MSALWebviewParameters(py)customWebview

However, it looks like you're using WKWebView configuration with MSAL. For B2C, we recommend using the default webview configuration instead. Please see more information here: https://docs.microsoft.com/en-us/azure/active-directory/develop/customize-webviews

**Comment by eltonjhony** [comment]
Hi @oldalton 

Thanks for the response!

Is the ```customWebView``` prepared to work with ```MSALWebviewType.wkWebView``` for B2C connections? I tested here and seems to not be working:
````
let webConfiguration = WKWebViewConfiguration()
let webView = WKWebView(frame: .zero, configuration: webConfiguration)

webViewParameters.webviewType = .wkWebView
webViewParameters.customWebview = webView
````
We know that is not the recommend solution, but we need to open the screen inside a WKWebView instead of a default web browser to meet UI requirements.

**Comment by oldalton** [comment]
You also need to display that WKWebView somewhere, by either adding it as a subview in code or adding it in the interface builder.

**Comment by eltonjhony** [comment]
Thank you @oldalton !
