### ISSUE TITLE
Show how you can prepopulate the login screen with username and password

### ISSUE THREAD

**Issue by azav** [Azure-Samples/active-directory-b2c-ios-swift-native-msal#27]
For our UI tests, we are used to entering the username and password for a local test user through code. When your samples use the SFSafariViewController, we are prevented from accessing the contents of these screens.

Until we can find out how to do this, we've got 300 broken UI tests.

Xcode 11.3, iOS.

**Comment by jennyf19** [comment]
fyi @oldalton

**Comment by oldalton** [comment]
Closing this issue as stale. Please reopen if needed.

**Comment by tomschulz** [comment]
"w/.NET and iOS we use app center and are able to pull users from our lab and automate the sign-in process. Are you looking to do something like that?"

I am looking for something like that. About to implement MSAL and all my tests are about to break.
