### ISSUE TITLE
Question: Intercept Custom WebView Events

### ISSUE THREAD

**Issue by ralexandre-ciandt** [Azure-Samples/active-directory-b2c-ios-swift-native-msal#29]
Hi!

I am trying to intercept a few WebView events and delegates but none of them seems to be called. Is this by security or there are a few more setups to do? Just to understand if it's a limitation and we cannot do it or if we can keep studying in order to put it to work.

Using a normal WebView opening a website all works, but passing it as a parameter as a custom WebView to MSAL they are not being called.

I need to get some information to natively log into our analytics tool like intercept a few button click methods for instance. I've already done all the setup =/

Tried first with the simple ones which are the WKNavigationDelegate to check if I can intercept the URL's being called, so later I could work with the userContentController and WKScriptMessageHandler to intercept button clicks and events with custom WKUserScript and a jsbridge in the WebView, or if at least we could make the jsbridge to work:

```
webView?.navigationDelegate = self

....

extension BaseOAuthWebViewController: WKNavigationDelegate {

    webview func webView(_ webView: WKWebView, decidePolicyFor navigationAction: WKNavigationAction, decisionHandler: @escaping (WKNavigationActionPolicy) -> Void) {
        // code here
    }
}
```

Thanks in advance!

**Comment by jennyf19** [comment]
cc: @oldalton

**Comment by oldalton** [comment]
Hi. MSAL itself will become a delegate for the webview that is why you're not able to intercept the events. Can you please provide a bit more information about scenarios you're trying to achieve?

**Comment by oldalton** [comment]
Closing this issue as stale. Please reopen if needed.
