### ISSUE TITLE
Edit profile Policy ask for login 

### ISSUE THREAD

**Issue by nitisha1** [Azure-Samples/active-directory-b2c-ios-swift-native-msal#3]
Hi,
i've successfully login and getting accesstoken but when i tap on edit profile it first ask for login and after login it goes to edit profile
Login -> Get Access Token - > Edit Profile -> Again ask for Login (which is not supposed to , i can login from another user and edit the profile of that user)
i debugged the the code , for edit profile it gets user by policy and i'm getting 2 user sometimes 1
 with u_id = b2c_signin & b2c_edit
Any help please ?

**Comment by parakhj** [comment]
We are working to resolve the issue, but as a workaround, you can replace the application.acquireToken() function inside editProfile() in VIewController.swift with

`application.acquireToken(forScopes: kScopes, user:thisUser, uiBehavior: MSALUIBehavior.MSALForceConsent, extraQueryParameters:nil)`

This will send prompt=consent instead of prompt=select_account in the request URL.

**Comment by nitisha1** [comment]
@parakhj - Thanks. i've replace acquireToken call with above change and its working for now.

**Comment by parakhj** [comment]
@nitisha1 i apologize for providing an incorrect workaround. We may end up using prompt=consent for another reason in the future, and this will break your app when the service updates. Let me get back to you with a better workaround.

**Comment by sharonSilicus** [comment]
@parakhj Any updates on the fix ? or a better workaround?

**Comment by parakhj** [comment]
Unfortunately not :( The best workaround is to store the idp claim (the claim that determines how the user signed in) and based on the claim, you can pass the proper domain_hint parameter. For example, if the idp claim is facebook.com, then during the edit profile call, you can add domain_hint=facebook.com in the request. The other option is to edit the profile by calling the Graph API (so basically don't use the Edit Profile policy at all)

**Comment by CA-hub** [comment]
@parakhj I'm facing the same issue Edit profile policy asking for login again. Any workaround 

also : -
            `let thisUser = try self.getUserByPolicy(withUsers: application.users(), forPolicy: kEditProfilePolicy)`

there is no such thing as **application.users()** in MSAL and also I could not find **MSALUser**

**Comment by parakhj** [comment]
@danieldobalian do we have any updates on the fix for this for iOS?

**Comment by jennyf19** [comment]
@nitisha1 @sharonSilicus @CA-hub @bketelsen Closing this, as it is outdated, but please re-open if the issue still persists. You should be able to set the prompt parameter to none, so no prompt is sent in the header to AAD B2C. This way AAD B2C will use the session cookies to determine if the user already has an active session and they won't be shown a login screen again. Here's an [example](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-prompt-behavior) with the MSAL.JS library, should be something similar w/obj-c, but i'm not able to find a doc on it. :/

**Comment by Shayila** [comment]
Hi,
I want to edit the profile for the user who is recently signed in,
How to skip the login page in MSAL custom Edit policy when the user is already signed-in?
