### ISSUE TITLE
Is it posible to add parameter to authorize api?

### ISSUE THREAD

**Issue by nguyenhuutinh** [Azure-Samples/active-directory-b2c-ios-swift-native-msal#32]
Hello,
I want to add custom parameter to custom policies.
is it posible to add it?
example: ip_override=103.247.92.0

https://abc.b2clogin.com/abc.onmicrosoft.com/oauth2/v2.0/authorize?p=B2C_1A_IP_Demomfa_signup_signin&client_id=abc&nonce=defaultNonce&redirect_uri=https%3A%2F%2Fjwt.ms&scope=openid&response_type=id_token&prompt=login&ip_override=103.247.92.0

thanks

**Comment by oldalton** [comment]
Thanks for the question. You can pass additional parameters as extra query parameters using this property: https://azuread.github.io/microsoft-authentication-library-for-objc/Classes/MSALInteractiveTokenParameters.html#/c:objc(cs)MSALInteractiveTokenParameters(py)extraQueryParameters. Hope it helps and sorry for a late reply. We generally recommend to open issues in the main MSAL repository to get more immediate help.

**Comment by oldalton** [comment]
Closing this issue as stale. Please reopen if needed.
