### ISSUE TITLE
How to limit scopes for idToken?

### ISSUE THREAD

**Issue by rbinrais** [Azure-Samples/active-directory-b2c-ios-swift-native-msal#33]
I need guidance on how to set the scope for idToken because I do not need access_token. 

Currently, the sample requires scope to be set even for an id_token. The empty scope or the scope of ``openid`` is not supported either.

``let kScopes: [String] = ["https://ultimatetest1.onmicrosoft.com/Read"] // This is a scope that you've configured your backend API to look for.
    ``

It would be helpful to get some guidance.

**Comment by oldalton** [comment]
This is currently not supported, but we have a feature tracking ticket to improve that: https://github.com/AzureAD/microsoft-authentication-library-for-objc/issues/852
