### ISSUE TITLE
Fails to parse userIdentities collection in native client iOS for Azure AD B2C and instead sends empty arrays

### ISSUE THREAD

**Issue by chadhasbrook** [Azure-Samples/active-directory-b2c-ios-swift-native-msal#35]
When using this sample, the token is not being properly parsed correctly with for the userIdentities collection returned from Azure AD B2C. We confirmed the same policy works OK with a web application as well as a test JWT app (the userIdentities field is populated - confirmed via MS Graph and with a test web app).

The token viewed inline appears to look like:

![image](https://user-images.githubusercontent.com/7002439/86953914-fd7e4a00-c109-11ea-85ea-7be7cf6abf98.png)

We are seeing this also on the MSAL Android as well - but we are able to repro it on with this sample.

**Comment by NerevarineRule** [comment]
@chadhasbrook Are you still seeing this issue?
