### ISSUE TITLE
Sign in with Apple does not work

### ISSUE THREAD

**Issue by nguyenhuutinh** [Azure-Samples/active-directory-b2c-ios-swift-native-msal#36]
Hi , Apple requires to support "Sign in with Apple" option to Azure B2C
Then we integrated it
 we tested with browser, it's ok,
but got problem when test on application. 
Got Stuck at appleid.apple.com
![Screen Shot 2020-07-09 at 2 15 00 PM](https://user-images.githubusercontent.com/4114159/87008897-9c7c7200-c1ee-11ea-89ad-c69944c23e7b.png)

and no callback in application.acquireToken

Do you have any suggestion?

Thanks

**Comment by jennyf19** [comment]
@nguyenhuutinh This issue seems to be fixed in iOS 13.4. 
->
"The original issue was an Apple bug and was caused by a race condition between Apple ID extension returning result and ASWebAuthenticationSession response handling (webkit was getting cancelled error -999)."

**Comment by nguyenhuutinh** [comment]
thanks
