### ISSUE TITLE
Authorization cycling for webviewType == .wkWebView/.safariViewController

### ISSUE THREAD

**Issue by pavelreva1998** [Azure-Samples/active-directory-b2c-ios-swift-native-msal#37]
Hello, 

I have authorization with MSAL within my project. The problem is the following, that it works fine with webviewType == .default, but it uses ASWebAuthenticationSession, which asks user permission for SSO, I don't have SSO and I just want to get rid of this prompt, the way I found is to set webviewType as wkWebView or safariViewController. But it seems, that, potentially, it requires some additional config, cause when I click even "Cancel" on the webview screen, it closes and opens again automatically.

So my question is how to avoid cycling for  .wkWebView/.safariViewController or how to get rid of prompt for ASWebAuthenticationSession

Thanks for your answer

**Comment by NerevarineRule** [comment]
@pavelreva1998 Is this issue resolved?
