### ISSUE TITLE
Authentication response received without expected accessToken

### ISSUE THREAD

**Issue by kiranSDM** [Azure-Samples/active-directory-b2c-ios-swift-native-msal#41]
I am trying to run the sample provided to get the token. I have replaced the values as specified in the readme file like client id, Tenant name as per the configuration received while registering the app.

I successfully able to open the page in safari which took input to login (Email/Password). Login was successful but I am receiving below error :
 **Error Domain=MSALErrorDomain Code=-50000 "(null)" UserInfo={MSALErrorDescriptionKey=Authentication response received without expected accessToken, MSALInternalErrorCodeKey=-42008, MSALCorrelationIDKey=CDCBABDA-856F-482A-96FE-538DC46729E9}**
![Screenshot 2020-10-09 at 11 23 09](https://user-images.githubusercontent.com/15884444/95548006-d3e30080-0a21-11eb-8f3a-ec592bc08578.png)

**Comment by jennyf19** [comment]
@kiranSDM thanks for opening the issue. Does doing a direct `git clone` of the repro and running it as-is work for you, or is the same here present there as well?

**Comment by kaisong1990** [comment]
@kiranSDM Thanks for your question, please refer to the following Github issues where the scope is invalid:

https://github.com/Azure-Samples/active-directory-b2c-ios-swift-native-msal/issues/24

https://github.com/Azure-Samples/active-directory-b2c-ios-swift-native-msal/issues/28
