### ISSUE TITLE
kgraphURI not accepted

### ISSUE THREAD

**Issue by gitforanand** [Azure-Samples/active-directory-b2c-ios-swift-native-msal#42]
IOS 14.1
SWIFT 5
When SINGUP_SIGNIN_Flow Triggered, 
<img width="328" alt="Screen Shot 2020-11-08 at 12 31 45 AM" src="https://user-images.githubusercontent.com/11406838/98457965-dc7e4200-2159-11eb-8daf-60a824776442.png">
<img width="444" alt="Screen Shot 2020-11-08 at 12 32 03 AM" src="https://user-images.githubusercontent.com/11406838/98457966-dd16d880-2159-11eb-8746-a4515751be3b.png">

'TID=406019 MSAL 1.1.7 iOS Sim 14.1 [2020-11-08 05:27:28 - 920EAB47-CB73-45A3-BA67-C2383BC5F8A6] [MSAL] -[MSALPublicClientApplication acquireTokenWithParameters:(
    "https://redacted.onmicrosoft.com/redacted/User.Read"
)
                                     extraScopesToConsent:(null)
                                                  account:Masked(null)
                                                loginHint:Masked(null)
                                               promptType:MSALPromptTypeSelectAccount
                                     extraQueryParameters:(null)
                                                authority:<MSALB2CAuthority: 0x600003a8a0e0>
                                              webviewType:MSALWebviewTypeDefault
                                            customWebview:No
                                            correlationId:(null)
                                             capabilities:(null)
                                            claimsRequest:(null)]
%@ TID=406019 MSAL 1.1.7 iOS Sim 14.1 [2020-11-08 05:27:28 - 920EAB47-CB73-45A3-BA67-C2383BC5F8A6] [MSAL] Beginning interactive flow.
TID=406019 MSAL 1.1.7 iOS Sim 14.1 [2020-11-08 05:27:28 - 920EAB47-CB73-45A3-BA67-C2383BC5F8A6] [MSAL] Beginning interactive flow.
%@ TID=406019 MSAL 1.1.7 iOS Sim 14.1 [2020-11-08 05:27:28 - 920EAB47-CB73-45A3-BA67-C2383BC5F8A6] [MSAL] Resolving authority: Masked(not-null), upn: Masked(null)
TID=406019 MSAL 1.1.7 iOS Sim 14.1 [2020-11-08 05:27:28 - 920EAB47-CB73-45A3-BA67-C2383BC5F8A6] [MSAL] Resolving authority: Masked(not-null), upn: Masked(null)
%@ TID=406019 MSAL 1.1.7 iOS Sim 14.1 [2020-11-08 05:27:28 - 920EAB47-CB73-45A3-BA67-C2383BC5F8A6] [MSAL] Resolved authority, validated: NO, error: 0
TID=406019 MSAL 1.1.7 iOS Sim 14.1 [2020-11-08 05:27:28 - 920EAB47-CB73-45A3-BA67-C2383BC5F8A6] [MSAL] Resolved authority, validated: NO, error: 0
%@ TID=406019 MSAL 1.1.7 iOS Sim 14.1 [2020-11-08 05:27:28] Start background app task with type 0
TID=406019 MSAL 1.1.7 iOS Sim 14.1 [2020-11-08 05:27:28] Start background app task with type 0
2020-11-08 00:27:28.626406-0500 oauthtest[16421:406019] Simulator user has requested new graphics quality: 100
2020-11-08 00:28:03.567826-0500 oauthtest[16421:406019] [BackgroundTask] Background Task 1 ("Interactive login"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.

**Comment by gitforanand** [comment]
let kTenantName = "redacted.onmicrosoft.com" // Your tenant name
    let kAuthorityHostName = "redacted.b2clogin.com" // Your authority host name
    let kClientID = "XXXXXXXX-1111-2222-3333-YYYYYYYYYYYY" // Your client ID from the portal when you created your application
    let kSignupOrSigninPolicy = "B2C_1_signup_signin" // Your signup and sign-in policy you created in the portal
    let kEditProfilePolicy = "b2c_1_edit_profile" // Your edit policy you created in the portal
    let kResetPasswordPolicy = "b2c_1_password_reset" // Your reset password policy you created in the portal
    let kGraphURI = "https://redacted.azurewebsites.net" // This is your backend API that you've configured to accept your app's tokens
    let kScopes: [String] = ["https://redacted.onmicrosoft.com/XXXXXXXX-1111-2222-3333-YYYYYYYYYYYY/User.Read"]
    //
    // DO NOT CHANGE - This is the format of OIDC Token and Authorization endpoints for Azure AD B2C.
    let kEndpoint = "https://%@/tfp/%@/%@"

**Comment by ameyapat** [comment]
@gitforanand Can you clarify what you're trying to do? What is the error that you're getting? Is the API you've specified in kGraphURI registered in your tenant? https://docs.microsoft.com/en-us/azure/active-directory-b2c/tutorial-desktop-app-webapi?tabs=app-reg-ga#add-a-web-api-application

**Comment by kaisong1990** [comment]
Closed it due to no response :)

Feel free to reopen it if there is still an issue
