### ISSUE TITLE
Building for iOS Simulator, but the linked framework 'MSAL.framework' was built for iOS.

### ISSUE THREAD

**Issue by mbondoso** [Azure-Samples/active-directory-b2c-ios-swift-native-msal#43]
Hi,

I used carthage as instructed but I get this error "Building for iOS Simulator, but the linked framework 'MSAL.framework' was built for iOS." and I cannot run any simulator.

**Comment by NerevarineRule** [comment]
There's an instance of MSAL.framework for iOS simulator. Linking it in the Link binary with libraries under build phase might help. Or perhaps Carthage doc could provide a way to change the MSAL.framework instance from the device target to the simulator target.

**Comment by mbondoso** [comment]
Ultimately I had to compile the code for simulator and link it. So it worked for the tests.

Thanks for the reply
