### ISSUE TITLE
iOS autofill sms code from the keyboard does not work

### ISSUE THREAD

**Issue by nguyenhuutinh** [Azure-Samples/active-directory-b2c-ios-swift-native-msal#44]
hi,

with sms input field, if we enter code manually , it works,

But if we tap the code in the top of keyboard (iOS), our form never can be completed.

![WhatsApp Image 2020-11-23 at 8 52 14 PM](https://user-images.githubusercontent.com/4114159/99974870-16934900-2dd4-11eb-8733-e78fa9ad0985.png)

We cannot modify this field. Can we add button there for complete the sms flow?

**Comment by NerevarineRule** [comment]
What is the autofill suggesting. Perhaps reach out to Apple directly for troubleshooting, as Apple owns this feature. Thanks.

**Comment by nguyenhuutinh** [comment]
yes, correct sms code. but the input complete trigger action was not fired

**Comment by oldalton** [comment]
This normally means that Input textfield is not properly configured. I'd recommend taking a look at Apple documentation: https://developer.apple.com/documentation/security/password_autofill/enabling_password_autofill_on_an_html_input_element?language=objc

**Comment by nguyenhuutinh** [comment]
hi, I found that  it is an issue on iOS 14. and you guys have fixed it.
