### ISSUE TITLE
Safari cannot open the page because the address is invalid

### ISSUE THREAD

**Issue by DaehyunLee** [Azure-Samples/active-directory-b2c-ios-swift-native-msal#46]
Hello, Thank you for the sample.
I'm encountering an issue and was wondering if someone can point me in the right direction.

<img width="1194" alt="20201214_132248463_iOS" src="https://user-images.githubusercontent.com/1912447/102086971-df1e2800-3de6-11eb-9acb-305072152d9a.png">

I've set things up referencing the read me and this post. (https://github.com/Azure-Samples/active-directory-b2c-ios-swift-native-msal/issues/28) 
Where would I be able to find out the invalid address?
Would love to dig in a bit more myself to find out what the invalid address is, but not sure where to go aside from debugging the MSAL library itself. 

This is the log that shows in the debug console.
`%@ TID=282805 MSAL 1.0.0 iOS 14.3 [2020-12-14 13:22:19 - 73701494-1B4E-469D-AD0E-F68CAD810634] [MSAL] Beginning interactive flow.
%@ TID=282805 MSAL 1.0.0 iOS 14.3 [2020-12-14 13:22:19 - 73701494-1B4E-469D-AD0E-F68CAD810634] [MSAL] Resolving authority: Masked(not-null), upn: Masked(null)
%@ TID=282805 MSAL 1.0.0 iOS 14.3 [2020-12-14 13:22:19 - 73701494-1B4E-469D-AD0E-F68CAD810634] [MSAL] Resolved authority, validated: NO, error: 0
%@ TID=282805 MSAL 1.0.0 iOS 14.3 [2020-12-14 13:22:19] Start background app task with type 0
2020-12-14 08:22:54.738659-0500 MSALiOSB2C[617:282805] [BackgroundTask] Background Task 5 ("Interactive login"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.`

**Comment by DaehyunLee** [comment]
The problem was the app registration being setup incorrectly.

Following the steps here solved it.
https://docs.microsoft.com/en-us/azure/active-directory-b2c/signin-appauth-ios?tabs=app-reg-ga

**Comment by aherciya** [comment]
@DaehyunLee Please let us know if there was something you found confusing in our documentation.

**Comment by ameyapat** [comment]
Closing as resolved
