### ISSUE TITLE
Not able to acquire token silent

### ISSUE THREAD

**Issue by ankitahuja0508** [Azure-Samples/active-directory-b2c-ios-swift-native-msal#51]
I tried saving account identifier while acquiring token interactively.
Now while getting account using below code does not return account
```
guard let account = try? application.account(forIdentifier: UserDefaults.standard.string(forKey: Constants.KEY_ACCOUNT)!) else {
                print("not able to get account")
                return
            }
```
That is needed to create  object for **MSALSilentTokenParameters** which again needs to be sent in function **acquireTokenSilent**

Can anyone please help me getting this solved. I am tired of implementing ' acquiring token silently '

**Comment by antrix1989** [comment]
hi @ankitahuja0508, could you please share MSAL logs? You can send them to sedemche@microsoft.com. Thanks!

**Comment by antrix1989** [comment]
You are getting:

`Keychain find status: -34018 /* A required entitlement isn't present. */`

Please add required keychain groups to your project Capabilities, see [here](https://github.com/AzureAD/microsoft-authentication-library-for-objc#configuring-msal).

**Comment by ankitahuja0508** [comment]
thanks
