### ISSUE TITLE
Is the B2C instance running?

### ISSUE THREAD

**Issue by mfcollins3** [Azure-Samples/active-directory-b2c-ios-swift-native-msal#56]
I'm trying to implement this in my Swift/iOS application using Xcode 12.5 and iOS 14.5. When I run try running the code against my tenant, I am getting "Safari cannot open the page because the address is invalid." I tried running the sample, but I'm getting a similar error and it appears that the B2C tenant that the sample is using is not running either. Is this sample still valid for using MSAL to authenticate against a B2C tenant?

**Comment by ameyapat** [comment]
@mfcollins3 Could you try again? We had the reply url in portal for our sample app misconfigured. It should be fixed now, thanks for noticing the issue.
