### ISSUE TITLE
Safari cannot open the page because the address is invalid

### ISSUE THREAD

**Issue by ljunquera** [Azure-Samples/active-directory-b2c-ios-swift-native-msal#59]
I downloaded the project, configured it according to [the documentation](https://github.com/Azure-Samples/active-directory-b2c-ios-swift-native-msal#configure-your-application). All the values were copied from Azure and match the pattern in the example values.

Added a platform configuration in Azure:
![image](https://user-images.githubusercontent.com/4500512/150687088-477ab8dc-2290-4376-b5c7-3bcd0bb6d4a3.png)

Here is the error I am getting:
![image](https://user-images.githubusercontent.com/4500512/150686823-e2e7ec9b-feb3-4da3-8dca-b981fe80e9b4.png)

and in the console:

> 2022-01-23 10:52:40.452041-0500 MSALiOSB2C[40720:4488790] [BackgroundTask] Background Task 1 ("Interactive login"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.

**Comment by antrix1989** [comment]
hi @ljunquera, what is the value of kAuthority?

**Comment by juan-arias** [comment]
@ljunquera, please also provide your `URL Schemes` section in the `info.plist` file.

**Comment by kaisong1990** [comment]
Closing the issue due to no response from customer

**Comment by DHFfighting** [comment]
I have the same issue, how to fix it ?

**Comment by DHFfighting** [comment]
> Closing the issue due to no response from customer

Hello, I have the same issue, how to fix it, can you contact me via email?, my email is dhf308618560@outlook.com  thanks

**Comment by uia9020** [comment]
how did you fix this issue? Im also getting this when I use my own credentials
