### ISSUE TITLE
Getting error while work with xcode 9.3

### ISSUE THREAD

**Issue by sunny131984** [Azure-Samples/active-directory-b2c-ios-swift-native-msal#6]
HI ,

We are trying to integrate the MSAL library with our project but in Xcode 9.3 we are getting lots of error due to syntax changes.  Please update the existing repository so anyone can use it with latest. i will try to figure out from my side. 

Thanks ,

**Comment by jennyf19** [comment]
@sunny131984 I think it's working better now. We are working harder to keep things updated and working.
