### ISSUE TITLE
Pod install in M1 Mac

### ISSUE THREAD

**Issue by electricpocket** [Azure-Samples/active-directory-b2c-ios-swift-native-msal#61]
pod install needs to be run in a Rosetta terminal window.
see https://osxdaily.com/2020/11/18/how-run-homebrew-x86-terminal-apple-silicon-mac/

**Comment by juan-arias** [comment]
Thank you @electricpocket, we will be updating the documentation.

**Comment by juan-arias** [comment]
Documentation has been updated.
