### ISSUE TITLE
acquireTokenSilent method returns  every time different token, even before session expire

### ISSUE THREAD

**Issue by reddy4** [Azure-Samples/active-directory-b2c-ios-swift-native-msal#63]
I'm trying to integrating MSAL into iOS Application using swift code, Followed below steps link:
https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-ios#register-your-application
acquireTokenSilent method returns  every time different token, even before session expire, as per my understand silent token should new token returns only when session got expired. 

Below my code snip:
===============On First time loading =====================================
 func initB2CClientApplication(vc:UIViewController)  {
        
        self.viewController = vc
        guard let authorityURL = URL(string:ADB2CStringConstants.kAuthorityURL) else {
            print("Unable to create authority URL")
            return
        }
        do {
            self.mSALB2CAuthority = try MSALB2CAuthority(url: authorityURL)
            let msalConfiguration = MSALPublicClientApplicationConfig(clientId: ADB2CStringConstants.kClientID, redirectUri: ADB2CStringConstants.kRedirectUri, authority: self.mSALB2CAuthority)
            msalConfiguration.knownAuthorities = [self.mSALB2CAuthority]
            
            self.applicationContext = try MSALPublicClientApplication(configuration: msalConfiguration)
            self.initWebViewParams()
            
        } catch  {
            print("Error:\(error)")
        }
    }
    func initWebViewParams() {
        self.webViewParamaters = MSALWebviewParameters(authPresentationViewController:  self.viewController)
    }

**_### After Login into ADB2C get the account details (verified account details its correct only) and passing to the below method._**
====================================================
func acquireTokenSilently(_ account : MSALAccount!, completionHandler:@escaping MSALAccountResult) {

        **let parameters = MSALSilentTokenParameters(scopes: ADB2CStringConstants.kScopesRead, account: account)**
        **parameters.authority = self.mSALB2CAuthority**
        **self.applicationContext.acquireTokenSilent(with: parameters) { (result, error) in**
            if let error = error {
               // print("Could not acquire token silently: \(error)")
                completionHandler(nil, error)
                return
            }
            guard let result = result else {
               // print("Could not acquire token: No result returned")
                completionHandler(nil, error)
                return
            }
            completionHandler(result, nil)
            **print("SILENT TOKEN:\(result.accessToken)")**
        }
    }
====================================================

**Comment by reddy4** [comment]
Any Help on above issue?

**Comment by mipetriu** [comment]
@reddy4 Do you mind providing a little more info: what issue are you seeing when running the sample?

And just to confirm, you're saying that you receive a different access token before the access token is expected to expire?

If you could provide some MSAL logs from your testing, that could help me take a closer look. Thank you!

**Comment by reddy4** [comment]
Step-1: Integrated MSAL into iOS application using cocoa-pods (MSAL version: 1.2.2) latest version.
Step-2: On app launch, initial setup is done as mentioned above **On First time loading**
Step-3: Calling **loadCurrentAccount** 
below method first it will check weather User already logged-in (ADB2C Login)OR NOT, If already logged-in get current account and pass through completion handler Otherwise pass as nil 
func loadCurrentAccount(completion: AccountCompletion? = nil) {
        
        let msalParameters = MSALParameters()
        msalParameters.completionBlockQueue = DispatchQueue.main
        self.applicationContext.getCurrentAccount(with: msalParameters, completionBlock: { (currentAccount, previousAccount, error) in
            if let error = error {
                print("Couldn't query current account with error: \(error)")
                return
            }
            
            if let currentAccount = currentAccount {
                print("Found a signed in account \(String(describing: currentAccount.username)). Updating data for that account...")
                self.updateCurrentAccount(account: currentAccount)
                if let completion = completion {
                    completion(currentAccount)
                }
                return
            }
            self.updateCurrentAccount(account: nil)
            if let completion = completion {
                completion(nil)
            }
        })
    }
    Step-4: If Above method returns with Account details then making another method call get silent token method **acquireTokenSilently**, Otherwise making call **acquireTokenInteractively** to get the access token.
    Below code snip which i tried:
    ===========

        self.loadCurrentAccount { (account) in
            
            guard let currentAccount = account else {
                self.acquireTokenInteractively { msalResult, error in
                    
                    if let errorr =  error  {
                        completionHandler(nil, errorr)
                        return
                    }
                    completionHandler(msalResult, error)
                }
                return
            }
            
            self.acquireTokenSilently(currentAccount) { msalResult, error in
                  if let error =  error  {
                    completionHandler(nil, error)
                    return
                }
                completionHandler(msalResult, error)
            }
        }
==========
     func acquireTokenInteractively(completionHandler:@escaping MSALAccountResult) {
        
        // #1
        let parameters = MSALInteractiveTokenParameters(scopes: ADB2CStringConstants.kScopes, webviewParameters: MSALWebviewParameters(authPresentationViewController: self.viewController))
            parameters.promptType = .login
            parameters.authority = self.mSALB2CAuthority
     
        // #2
        self.applicationContext.acquireToken(with: parameters) { (result, error) in
            // #3
            if let error = error {
                print("Could not acquire token: \(error)")
                completionHandler(nil, error)
                return
            }
            guard let result = result else {
                print("Could not acquire token: No result returned")
                completionHandler(nil, error)
                return
            }
            // #4
           // print("Access token is \(result.accessToken)")
            self.updateCurrentAccount(account: result.account)
            
            print(" TOKEN:\(result.accessToken)")

            //MARK: Saving token
           // let tokenSavedStatus = self.saveToken(token: result.accessToken)
           // print(tokenSavedStatus)
            completionHandler(result, nil)
        }
    }
    =============
     func acquireTokenSilently(_ account : MSALAccount!, completionHandler:@escaping MSALAccountResult) {
        
        //let parameters = MSALSilentTokenParameters(scopes: ADB2CStringConstants.kScopesRead, account: account)
       // parameters.authority = self.mSALB2CAuthority
        
        let parameters = MSALSilentTokenParameters(scopes: ADB2CStringConstants.kScopes, account: account)
        self.applicationContext.acquireTokenSilent(with: parameters) { (result, error) in
            if let error = error {
                print("Could not acquire token silently: \(error)")
                completionHandler(nil, error)
                return
            }
            guard let result = result else {
                print("Could not acquire token: No result returned")
                completionHandler(nil, error)
                return
            }
            
        //    print("SILENT TOKEN:\(result.accessToken)")
            
            //MARK: Saving token
           // let tokenSavedStatus = self.saveToken(token: result.accessToken)
          //  print(tokenSavedStatus)
            completionHandler(result, nil)
        }
    }
    ===========
    In  above **acquireTokenInteractively**. **acquireTokenSilently** two method returns Different token every time, even before session expires.

**Comment by reddy4** [comment]
At time only one method will executed based on user already  logged-in. if already logged-in **acquireTokenSilently** method will executes, if not **acquireTokenInteractively** method will executes.
Every time getting different token, even before session expires.

**Comment by antrix1989** [comment]
@reddy4 could you please capture MSAL logs and send them to sedemche@microsoft.com?

**Comment by mipetriu** [comment]
@reddy4 Closing issue due to no response. If you'd like to further discuss the issue, please send logs to identity-apple-eng@microsoft.com and re-open the issue. Thanks!
