### ISSUE TITLE
Safari cannot open the page because the address is invalid

### ISSUE THREAD

**Issue by DHFfighting** [Azure-Samples/active-directory-b2c-ios-swift-native-msal#65]
When I use some keys such as ktenantname, kautrityhostname and kclientid, when I click authorize to log in, Safari browser pops up and prompts Safari can not open the page because the address is invalid I don't know where there is a problem. I hope to get help. Thank you
![Simulator Screen Shot - iPhone 13 mini - 2022-08-24 at 16 50 29](https://user-images.githubusercontent.com/18415689/186374990-5359cb63-7eef-4b9c-a146-16d252b7a2d1.png)

**Comment by uia9020** [comment]
how did you fix this issue? Im also getting this when I use my own credentials

**Comment by johnlabrookstonecm** [comment]
Still having this issue, how did you fix it?
