### ISSUE TITLE
Add support for Swift Package Manager

### ISSUE THREAD

**Issue by mruvim** [Azure-Samples/active-directory-b2c-ios-swift-native-msal#67]
Please add Swift Package Manger support to `MSALiOSB2C` library.

**Comment by mipetriu** [comment]
Hello @mruvim, the MSAL iOS B2C sample app uses the MSAL library, which should have Swift Package Manager support. Are you able to get MSAL working with Swift Package Manager?

**Comment by ameyapat** [comment]
instructions for adding MSAL swift package : https://github.com/AzureAD/microsoft-authentication-library-for-objc#using-swift-packages

**Comment by mruvim** [comment]
Great thank you, closing ticket
