### ISSUE TITLE
I am facing one problem with the azure console when I am resetting the password from the azure console the token is not invalidating on the device/simulator.

### ISSUE THREAD

**Issue by tosif-kanunga** [Azure-Samples/active-directory-b2c-ios-swift-native-msal#69]
applicationContext.acquireToken(with: parameters) { (result, error) in
            
            if (error != nil) || result == nil {
                print("Handle error")
                // Handle error
            } else {
                print("Token valid")
                // Token valid
            }
}
I am using this to verify the token

**Comment by swasti29** [comment]
The token remains valid until expired. The is by design.
