### ISSUE TITLE
Safari cannot open the page because the address is invalid

### ISSUE THREAD

**Issue by uia9020** [Azure-Samples/active-directory-b2c-ios-swift-native-msal#70]
I have seen this issue is raised by couple of guys but I could not resolve the issue. 
Im getting this when I use my own credentials

![Screenshot 2024-02-27 at 09 50 09](https://github.com/Azure-Samples/active-directory-b2c-ios-swift-native-msal/assets/3676602/4a9c8b34-de8a-4c6e-91c0-68baae9feec9)

**Comment by Veena11** [comment]
@uia9020 , Likely reasons for this issue are : 

1. App not registered correctly, please follow the instructions here for app registration : https://github.com/Azure-Samples/active-directory-b2c-ios-swift-native-msal?tab=readme-ov-file#app-registration
2. Info.plist not configured correctly , please follow the instructions here:  https://github.com/Azure-Samples/active-directory-b2c-ios-swift-native-msal?tab=readme-ov-file#configure-your-application

Please let us know if the issue still persists after verifying the above two.

**Comment by uia9020** [comment]
it was Info.plist not configured correctly. Thank you

**Comment by uia9020** [comment]
it was Info.plist not configured correctly. Thank you
