### ISSUE TITLE
Support OKTA sign in

### ISSUE THREAD

**Issue by manghwanitin** [Azure-Samples/active-directory-b2c-ios-swift-native-msal#71]
Hello,
We have a native iOS application where we are authenticating users via OKTA login.
We have a new required to integration intune MAM in our app.
Looking at all the samples, it looks like user needs to be authenticated separately for using Intune policy(authentication can be done via MSAL).
So for the first time user will need to go through authentication twice(first using OKTA and second using MSAL)
Is there a way we can integrate OKTA login in MSAL and user needs to be authenticated only once?

**Comment by manghwanitin** [comment]
Any further updates on this please?

**Comment by kaisong1990** [comment]
Hi @manghwanitin you mentioned

> Is there a way we can integrate OKTA login in MSAL and user needs to be authenticated only once?

Could you clarify what integrate means here?

If you referred to integration from a client library/code perspective, I don't think we can do this
Maybe try federated login?
https://www.okta.com/identity-101/what-is-federated-identity/

**Comment by jasoncoolmax** [comment]
close due to lack of activity.
