### ISSUE TITLE
Sample Project - MSALiOSB2C is not working

### ISSUE THREAD

**Issue by sathishTkumar** [Azure-Samples/active-directory-b2c-ios-swift-native-msal#8]
Hi Author,
I downloaded the active-directory-b2c-ios-swift-native-msal as zip.
After unzipping, I proceeded with the Installation steps specified in Readme.md.
Once its done, I executed the code with the default configuration values(I did not integrate my configuration values) and I was launched in the Sign-In page.
Since I do not have any account to Sign-In, I went for Sign-Up.
Once I tapped the Create Button, the application crashed.

Help me in addressing this issue. Thanks

**Comment by danieldobalian** [comment]
Sorry for delayed response, we'll be taking a look at the sample and re-writing a large portion of it. Expect an update soon.
