### ISSUE TITLE
Xcode 9.3 issue after tapping Login button.

### ISSUE THREAD

**Issue by iHackSubhodip** [Azure-Samples/active-directory-b2c-ios-swift-native-msal#9]
Hi Author,

I downloaded the active-directory-b2c-ios-swift-native-msal as zip.
Once its done, I executed the code with the default configuration values(I did not integrate my configuration values) and I was launched in the Sign-In page.
Since I do not have any account to Sign-In, I went for Sign-Up.
Once I tapped the Create Button/Sign-In button, the application crashed.

Help me in addressing this issue. Thanks

**Comment by jennyf19** [comment]
@iHackSubhodip have you tried w/the latest version? sorry there was no response here. If you still have issues, please re-open. thanks.
